name: JD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9086022
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71923736-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFB466'
    - '#BECEE1'
    - '#28160D'
    - '#654B32'
    - '#FFFFFB'
  brandStrength: 0.9946237
  lightness: 0.7745553
  saturation: 0.3849846
  rhythmicContrast: 0.01598629
purpose: []
